name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version"
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Set up build environment
        run: |
          sudo apt update
          DEBIAN_FRONTEND=noninteractive sudo apt install -y gcc make
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Build omc decoder
        run: make

      - name: Update current version
        run: git tag "${{ inputs.version }}"

      - name: Push changes to repo
        uses: ad-m/github-push-action@master
        with:
          tags: true
          github_token: ${{ secrets.TOKEN }}

      - name: Upload release assets
        uses: softprops/action-gh-release@v3
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: "${{ inputs.version }}"
          name: "${{ inputs.version }}"
          files: ./out/omc-decoder
